services:
  mysql:
    image: mysql:8.4
    container_name: orderpulse-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: orderpulse
      MYSQL_USER: orderpulse
      MYSQL_PASSWORD: orderpulsepassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: